
CREATE TABLE AMFT_PARAM_MASTER
(
    PARAM_ID INT,
    PARAM_NAME VARCHAR(50) NOT NULL,
	CONSTRAINT AMFT_PARAM_MASTER_PK PRIMARY KEY (PARAM_ID)
);



CREATE TABLE AMFT_FILE_TRANSFER_MASTER
(
	FILE_TRANSFER_ID INT,	
	APPLICATION_NAME VARCHAR(100) NOT NULL,
	TRANSFER_TYPE	VARCHAR(100) NOT NULL,

	CONSTRAINT AMFT_FILE_TRANSFER_PK PRIMARY KEY (FILE_TRANSFER_ID)
);


CREATE TABLE AMFT_CONFIG_PARAMS
(
	FILE_TRANSFER_ID	INT,
	PARAM_ID		INT,
	PARAM_VALUE		VARCHAR(500),
	CONSTRAINT AMFT_CONFIG_APP_PARAMS_PK 	PRIMARY KEY (FILE_TRANSFER_ID, PARAM_ID),
	CONSTRAINT AMFT_CONFIG_APP_PARAMS_FK1 	FOREIGN KEY (FILE_TRANSFER_ID) REFERENCES AMFT_FILE_TRANSFER_MASTER(FILE_TRANSFER_ID),
	CONSTRAINT AMFT_CONFIG_APP_PARAMS_FK2 	FOREIGN KEY (PARAM_ID) 	 	REFERENCES AMFT_PARAM_MASTER(PARAM_ID)
);

CREATE TABLE AMFT_JOB_HISTORY
(
	CORELATION_ID	INT,
    JOB_ID          INT,
	FILE_TRANSFER_ID	INT,
	FAILOVER_FTS_ID		INT,
	SOURCE_FILE_PATH       VARCHAR(1000),
    SOURCE_FILE_NAME		VARCHAR(200),
    SOURCE_FILE_SIZE       INT,
    SOURCE_FILE_CHECKSUM        INT,
	SOURCE_DOWNLOAD_TIME TIMESTAMP,
    TARGET_FILE_PATH       VARCHAR(1000),
	TARGET_FILE_NAME		VARCHAR(200),
    TARGET_FILE_SIZE       INT,
    TARGET_FILE_CHECKSUM        INT,
    TARGET_UPLOAD_TIME TIMESTAMP,
    STATUS          VARCHAR(10),
    COMMENTS        VARCHAR(512),
	RETRY_COUNT		INT,
    CREATED_TIME    TIMESTAMP,
    UPDATED_TIME    TIMESTAMP,
	
	CONSTRAINT AMFT_JOB_HISTORY_FK1 	FOREIGN KEY (FILE_TRANSFER_ID) REFERENCES AMFT_FILE_TRANSFER_MASTER(FILE_TRANSFER_ID)
);



CREATE SEQUENCE AMFT_FILE_TRANSFER_ID_SEQ
START WITH   1
INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE AMFT_JOB_HISTORY_JOB_ID_SEQ
START WITH   1
INCREMENT BY   1
 NOCACHE
 NOCYCLE;